### ISSUE TITLE
贡献一个download_model的py3版本

### ISSUE THREAD

**Issue by cuihee** [abars/YoloKerasFaceDetection#5]
# Download pretrained model

import os
import sys
from urllib import request

def main(argv):
	output_path = "./pretrain/"
	if not os.path.isdir(output_path):
		os.mkdir(output_path)
	with open(output_path+'agegender_age101_squeezenet.hdf5', 'wb') as f:
		f.write(request.urlopen("http://www.abars.biz/keras/agegender_age101_squeezenet.hdf5").read())
		f.close()
		print("1/3")
	with open(output_path+'agegender_gender_squeezenet.hdf5', 'wb') as f:
		f.write(request.urlopen("http://www.abars.biz/keras/agegender_gender_squeezenet.hdf5").read())
		f.close()
		print("2/3")
	with open(output_path+'yolov2_tiny-face.h5', 'wb') as f:
		f.write(request.urlopen("http://www.abars.biz/keras/yolov2_tiny-face.h5").read())
		f.close()
		print("3/3")

if __name__ == '__main__':
	print("start...")
	main(sys.argv[1:])

**Comment by abars** [comment]
Thanks. I merged your code.
